name: "@minions-oss-quality/web"
project_scope: child
child_type: web-app
parent_project: minions-oss-quality-workspace
description: "Standard compliance definition for @minions-oss-quality/web"
priority: high
deploy_url: null
tags: null
category: minion-toolbox
